"""
GitHub Escalation Node — GitHub Integration via Swytchcode.

Creates a GitHub issue when the Notion KB doesn't have an answer.
This is the "Knowledge Gap Detection" innovation feature — it automatically
identifies gaps in the company's documentation and files issues for the
docs/engineering team to address.
"""
from swytchcode_runtime import exec as swy_exec
from src.config import Config


def run(state: dict) -> dict:
    """
    Create a GitHub issue for knowledge base gaps.

    Swytchcode tools used:
        - github.issue.create  (write)

    Innovation feature:
        When the Notion KB doesn't contain an answer for a customer query,
        the agent auto-creates a GitHub issue titled "KB Gap: [topic]"
        for the documentation team. This creates a feedback loop that
        continuously improves the knowledge base.
    """
    log = list(state.get("execution_log", []))
    subject = state.get("email_subject", "Unknown Issue")
    category = state.get("issue_category", "unknown")
    sentiment = state.get("sentiment", "neutral")
    priority = state.get("priority", "medium")
    keywords = state.get("keywords", [])

    log.append("🐛 [GitHub] Creating KB gap issue...")

    try:
        # Build rich issue body
        body_lines = [
            "## 📋 Knowledge Base Gap Detected",
            "",
            "A customer support query could not be resolved from the existing knowledge base.",
            "Please create a KB article addressing this topic.",
            "",
            "### Details",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| **Category** | `{category}` |",
            f"| **Priority** | `{priority}` |",
            f"| **Sentiment** | `{sentiment}` |",
            f"| **Keywords** | {', '.join(f'`{k}`' for k in keywords) or 'N/A'} |",
            "",
            "### Customer Query",
            "",
            f"> **Subject:** {subject}",
            "",
            f"> {state.get('email_body', '(no body)')[:1000]}",
            "",
            "---",
            "*This issue was auto-generated by the AI Support Agent via Swytchcode.*",
        ]

        # Set labels based on priority
        labels = ["kb-gap", "auto-generated"]
        if priority in ("high", "critical"):
            labels.append("urgent")

        result = swy_exec("github.issue.create", {
            "body": {
                "title": f"KB Gap: {category} — {subject[:80]}",
                "body": "\n".join(body_lines),
                "labels": labels,
            },
            "params": {
                "owner": Config.GITHUB_OWNER,
                "repo": Config.GITHUB_REPO,
            }
        })

        res_data = result.get("data", result) if isinstance(result, dict) else {}
        issue_number = res_data.get("number", "?")
        issue_url = res_data.get("html_url", "")

        if issue_number != "?":
            log.append(f"✅ [GitHub] Created issue #{issue_number}: KB Gap")
        else:
            log.append(f"⚠️  [GitHub] Issue creation response: {res_data.get('message', 'pending')}")

        return {
            **state,
            "github_issue_id": str(issue_number),
            "github_issue_url": issue_url,
            "execution_log": log,
        }

    except Exception as e:
        log.append(f"❌ [GitHub] Issue creation error: {e}")
        return {
            **state,
            "github_issue_id": None,
            "github_issue_url": None,
            "execution_log": log,
        }
