"""
GitHub Escalation Node — GitHub Integration via Swytchcode + REST fallback.

Creates a GitHub issue when the Notion KB doesn't have an answer.
This is the "Knowledge Gap Detection" innovation feature — it automatically
identifies gaps in the company's documentation and files issues for the
docs/engineering team to address.
"""
import os
from src.config import Config

try:
    from swytchcode_runtime import exec as swy_exec
    _HAS_SWYTCHCODE = True
except Exception:
    _HAS_SWYTCHCODE = False


def _create_via_rest(title: str, body: str, labels: list) -> dict:
    """
    Direct GitHub REST API v3 call — does NOT require Swytchcode.
    Returns dict with 'number' and 'html_url' on success, or raises.
    """
    import requests

    token = os.getenv("GITHUB_TOKEN", Config.GITHUB_OWNER)
    owner = Config.GITHUB_OWNER
    repo  = Config.GITHUB_REPO

    # Guard: refuse placeholder tokens
    if not token or token.startswith("your_"):
        raise ValueError(
            f"GITHUB_TOKEN is not set or is a placeholder ('{token[:30]}...'). "
            "Please create a Personal Access Token at https://github.com/settings/tokens "
            "with 'repo' scope and add it to your .env file as GITHUB_TOKEN=<token>"
        )

    url = f"https://api.github.com/repos/{owner}/{repo}/issues"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {"title": title, "body": body, "labels": labels}

    resp = requests.post(url, headers=headers, json=payload, timeout=15)

    if resp.status_code == 201:
        data = resp.json()
        return {"number": data["number"], "html_url": data["html_url"]}
    elif resp.status_code == 401:
        raise ValueError("GitHub token is invalid or expired. Generate a new one at https://github.com/settings/tokens")
    elif resp.status_code == 404:
        raise ValueError(
            f"GitHub repo '{owner}/{repo}' not found or token lacks access. "
            "Make sure the repo exists and your token has 'repo' scope."
        )
    elif resp.status_code == 410:
        raise ValueError(f"GitHub issues are disabled on repo '{owner}/{repo}'.")
    else:
        raise RuntimeError(f"GitHub API error {resp.status_code}: {resp.text[:300]}")


def run(state: dict) -> dict:
    """
    Create a GitHub issue for knowledge base gaps.

    Tries Swytchcode first, then falls back to direct REST API.

    Innovation feature:
        When the Notion KB doesn't contain an answer for a customer query,
        the agent auto-creates a GitHub issue titled "KB Gap: [topic]"
        for the documentation team. This creates a feedback loop that
        continuously improves the knowledge base.
    """
    log = list(state.get("execution_log", []))
    subject  = state.get("email_subject", "Unknown Issue")
    category = state.get("issue_category", "unknown")
    sentiment= state.get("sentiment", "neutral")
    priority = state.get("priority", "medium")
    keywords = state.get("keywords", [])

    log.append("🐛 [GitHub] Creating KB gap issue...")

    # ── Build issue content ──────────────────────────────────────
    body_lines = [
        "## 📋 Knowledge Base Gap Detected",
        "",
        "A customer support query could not be resolved from the existing knowledge base.",
        "Please create a KB article addressing this topic.",
        "",
        "### Details",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Category** | `{category}` |",
        f"| **Priority** | `{priority}` |",
        f"| **Sentiment** | `{sentiment}` |",
        f"| **Keywords** | {', '.join(f'`{k}`' for k in keywords) or 'N/A'} |",
        "",
        "### Customer Query",
        "",
        f"> **Subject:** {subject}",
        "",
        f"> {state.get('email_body', '(no body)')[:1000]}",
        "",
        "---",
        "*This issue was auto-generated by the AI Support Agent via Swytchcode.*",
    ]
    title  = f"KB Gap: {category} — {subject[:80]}"
    body   = "\n".join(body_lines)
    labels = ["kb-gap", "auto-generated"]
    if priority in ("high", "critical"):
        labels.append("urgent")

    issue_number = None
    issue_url    = None

    # ── 1. Try Swytchcode ────────────────────────────────────────
    if _HAS_SWYTCHCODE:
        try:
            result = swy_exec("github.issue.create", {
                "body": {"title": title, "body": body, "labels": labels},
                "params": {"owner": Config.GITHUB_OWNER, "repo": Config.GITHUB_REPO},
            })
            res_data = result.get("data", result) if isinstance(result, dict) else {}
            issue_number = res_data.get("number")
            issue_url    = res_data.get("html_url", "")
            if issue_number:
                log.append(f"✅ [GitHub/Swytchcode] Created issue #{issue_number}")
        except Exception as swy_err:
            log.append(f"ℹ️  [GitHub] Swytchcode attempt: {swy_err}")

    # ── 2. Fall back to direct REST ──────────────────────────────
    if not issue_number:
        try:
            data = _create_via_rest(title, body, labels)
            issue_number = data["number"]
            issue_url    = data["html_url"]
            log.append(f"✅ [GitHub/REST] Created issue #{issue_number}: {issue_url}")
        except Exception as rest_err:
            log.append(f"❌ [GitHub] REST fallback failed: {rest_err}")

    return {
        **state,
        "github_issue_id":  str(issue_number) if issue_number else None,
        "github_issue_url": issue_url,
        "execution_log":    log,
    }
