import { AgentResponse, TopologyNode } from '../types';

export const INITIAL_TOPOLOGY_NODES: TopologyNode[] = [
  {
    id: 'weather',
    index: 0,
    name: 'OpenWeather',
    service: 'Atmospheric Telemetry',
    description: 'Retrieves current observations, barometric trends, and 24h temperature curves.',
    status: 'idle',
    iconName: 'CloudSun',
  },
  {
    id: 'gmail',
    index: 1,
    name: 'Gmail',
    service: 'Calendar Anchors',
    description: 'Scans inbox for flight tickets, meetings, and outdoor commitments.',
    status: 'idle',
    iconName: 'Mail',
  },
  {
    id: 'jira',
    index: 2,
    name: 'Jira Workload',
    service: 'Sprint Engineering',
    description: 'Aggregates open sprint tickets, priority blockers, and estimated dev hours.',
    status: 'idle',
    iconName: 'CheckSquare',
  },
  {
    id: 'github',
    index: 3,
    name: 'GitHub Reviews',
    service: 'Code Collaboration',
    description: 'Tracks pending pull requests, stale reviews (>2 days), and assigned repo issues.',
    status: 'idle',
    iconName: 'GitPullRequest',
  },
  {
    id: 'ai_advisor',
    index: 4,
    name: 'Gemini AI',
    service: 'Decision Engine',
    description: 'Synthesizes weather hazards, sprint load, and transit risks into an optimal day plan.',
    status: 'idle',
    iconName: 'BrainCircuit',
  },
  {
    id: 'notion',
    index: 5,
    name: 'Notion',
    service: 'Knowledge Base',
    description: 'Generates permanent briefing pages with rich markdown formatting.',
    status: 'idle',
    iconName: 'BookOpen',
  },
  {
    id: 'slack',
    index: 6,
    name: 'Slack',
    service: 'Team Dispatcher',
    description: 'Broadcasts Block Kit executive summary and WFH verdict to engineering channels.',
    status: 'idle',
    iconName: 'MessageSquare',
  },
  {
    id: 'resend',
    index: 7,
    name: 'Resend',
    service: 'Executive Digest',
    description: 'Dispatches styled HTML executive briefing digest to user inbox.',
    status: 'idle',
    iconName: 'Send',
  },
];

export const MOCK_RESPONSES: Record<string, AgentResponse> = {
  // Scenario 1: Storm Warning in London
  storm_warning: {
    city: 'London',
    weather_summary: '🌧️ London: Heavy rain & gusty winds | 14.5°C (feels like 12.8°C) | Humidity: 88% | Wind: 6.8 m/s',
    temperature_c: 14.5,
    feels_like_c: 12.8,
    humidity: 88,
    wind_speed: 6.8,
    weather_condition: 'Rain',
    weather_icon: '10d',
    weather_score: 32,
    risk_level: 'high',
    forecast_summary: '24h forecast: Continuous precipitation, peak gusts at 14:00 | Temps: 12°C – 15°C',
    weather_alerts: [
      '⚠️ Met Office Yellow Warning: Sustained heavy rainfall and transit disruption across Greater London.',
      '⚠️ Flooding alert on surface transit routes and rail delays expected.',
    ],
    ai_summary:
      'Severe weather front active across London with continuous rainfall and gale-force wind gusts. Commute transit corridors are facing severe delays. Given 2 urgent Jira tickets requiring dedicated focus, working from home eliminates commute hazards while maximizing engineering throughput.',
    go_to_office: 'wfh',
    office_reason: 'Severe rainstorm advisories and major transit delays make remote work the safest and most productive choice.',
    estimated_productive_hours: 6.5,
    recommendations: [
      'Switch all in-person meetings to Google Meet / Zoom.',
      'Protect electrical setup; potential localized power surges during peak gusts.',
      'Batch deep-work sessions in the morning before storm peak at 14:00.',
      'Keep indoor lighting high to counteract heavy overcast gloom.',
    ],
    outfit_suggestion: 'Comfortable indoor layers, warm knitwear, and keep waterproof shell handy if stepping outside.',
    activity_adjustments: [
      'Converted 11:30 AM client coffee at Soho to virtual conference.',
      'Moved evening gym commute to indoor home stretching routine.',
    ],
    gmail_events: [
      {
        subject: 'London Engineering Sync & Standup',
        from: 'techlead@swytchcode.dev',
        snippet: 'Standup room link updated to virtual due to travel warnings.',
        date: '2026-09-26T09:30:00Z',
        has_outdoor: false,
        has_travel: false,
      },
    ],
    gmail_summary: '📋 1 calendar sync detected · Switched to virtual room',
    has_outdoor_plans: false,
    has_travel_plans: false,
    jira_tickets: [
      {
        key: 'CORE-204',
        summary: 'Hotfix: WebSocket reconnect jitter on mobile clients',
        priority: 'Highest',
        status: 'In Progress',
        issue_type: 'Bug',
        estimated_hours: 3.5,
      },
      {
        key: 'CORE-211',
        summary: 'Implement payload chunking for Notion exporter',
        priority: 'High',
        status: 'To Do',
        issue_type: 'Task',
        estimated_hours: 2.5,
      },
    ],
    jira_estimated_hours: 6.0,
    jira_summary: '📋 2 high-priority sprint issues · ~6.0h total workload',
    github_prs: [
      {
        type: 'PR',
        number: 44,
        title: 'fix(ws): Backoff reconnect timing with jitter',
        author: 'iakankshaa',
        state: 'open',
        draft: false,
        days_old: 2,
        url: 'https://github.com/swytchcode/day-planner/pull/44',
        estimated_hours: 1.5,
      },
    ],
    github_issues: [
      {
        type: 'Issue',
        number: 108,
        title: 'Intermittent socket drop on mobile reconnect',
        state: 'open',
        days_old: 1,
        url: 'https://github.com/swytchcode/day-planner/issues/108',
        author: 'qa-bot',
        est_hours: 1.0,
      },
    ],
    github_estimated_hours: 2.5,
    github_summary: '🐙 1 open PR review & 1 assigned triage issue · ~2.5h workload',
    day_plan_timeline: [
      {
        id: 'block-1',
        time: '08:30 – 09:30',
        activity: 'Morning Atmospheric Briefing & Triage',
        category: 'general',
        location: 'Home Office',
        context: 'Review weather alerts and prioritize sprint blocker CORE-204',
        completed: true,
      },
      {
        id: 'block-2',
        time: '09:30 – 10:00',
        activity: 'Engineering Virtual Standup',
        category: 'meeting',
        location: 'Google Meet',
        context: 'Brief team on remote status and storm precautions',
        completed: true,
      },
      {
        id: 'block-3',
        time: '10:00 – 12:30',
        activity: '[Jira CORE-204] Fix WebSocket reconnect jitter',
        category: 'deep_work',
        location: 'Workstation',
        context: 'High-focus implementation of exponential backoff',
        completed: false,
      },
      {
        id: 'block-4',
        time: '12:30 – 13:30',
        activity: 'Lunch & Indoor Mental Recharge',
        category: 'break',
        location: 'Kitchen / Lounge',
        context: 'Avoid outdoor transit during heavy rainfall',
        completed: false,
      },
      {
        id: 'block-5',
        time: '13:30 – 15:00',
        activity: '[GitHub PR #44] Code Review & CI Validation',
        category: 'deep_work',
        location: 'Workstation',
        context: 'Verify peer test coverage and approve PR',
        completed: false,
      },
      {
        id: 'block-6',
        time: '15:00 – 17:00',
        activity: '[Jira CORE-211] Notion rich-text block chunking',
        category: 'deep_work',
        location: 'Workstation',
        context: 'Split blocks exceeding 1900 character limit',
        completed: false,
      },
      {
        id: 'block-7',
        time: '17:00 – 17:30',
        activity: 'Sprint Wrap-up & Daily Async Log',
        category: 'general',
        location: 'Home Office',
        context: 'Publish Notion page and send Slack wrap-up',
        completed: false,
      },
    ],
    notion_logged: true,
    notion_page_url: 'https://notion.so/swytchcode/London-Storm-Briefing-2026-09-26',
    slack_message_sent: true,
    email_sent: true,
    resend_message_id: 're_london_storm_9921',
    execution_log: [
      '⚡ [LangGraph] Pipeline initialized for scenario: storm_warning (London)',
      '🌦️ [OpenWeather] 14.5°C Rain detected | Alert flag active',
      '📬 [Gmail] 1 meeting parsed · Adjusted to virtual',
      '📋 [Jira] 2 sprint tickets fetched (6.0h estimated)',
      '🐙 [GitHub] 1 open PR & 1 issue parsed (2.5h estimated)',
      '🧠 [Gemini AI] Evaluated transit risk (88%) vs workload: WFH verdict synthesized',
      '📓 [Notion] Daily Briefing page created successfully',
      '📢 [Slack] Alert dispatched to #engineering-daily',
      '📧 [Resend] Executive HTML digest delivered to developer@swytchcode.dev',
      '🏁 [LangGraph] Pipeline complete with 0 errors (782ms)',
    ],
    processed_at: '2026-09-26T00:20:00.000Z',
  },

  // Scenario 2: Delhi Flight Travel Day
  travel_day: {
    city: 'Delhi',
    weather_summary: '☀️ Delhi: Clear skies, moderate morning haze | 28.2°C (feels like 30.5°C) | Humidity: 54% | Wind: 2.1 m/s',
    temperature_c: 28.2,
    feels_like_c: 30.5,
    humidity: 54,
    wind_speed: 2.1,
    weather_condition: 'Clear',
    weather_icon: '01d',
    weather_score: 76,
    risk_level: 'medium',
    forecast_summary: '24h forecast: Clear skies throughout day, rising to 34°C by 14:00 | Temps: 24°C – 34°C',
    weather_alerts: [
      'ℹ️ Morning transit notice: Fog/haze minimal, runway visual range normal at IGI Airport.',
    ],
    ai_summary:
      'Delhi weather is favorable for travel with calm winds and high visibility. An early 06:00 AM flight requires leaving for Terminal 3 by 03:45 AM. Recommend hybrid schedule: early transit followed by remote workspace setup at destination hotel or airport lounge.',
    go_to_office: 'hybrid',
    office_reason: 'Early airport departure anchors the morning; transition to remote deep work post-arrival.',
    estimated_productive_hours: 5.5,
    recommendations: [
      'Pre-book cab by 03:30 AM to ensure timely arrival at IGI T3.',
      'Keep digital boarding pass and passport/ID readily accessible.',
      'Utilize 2-hour flight duration for offline code review on GitHub PRs.',
      'Hydrate frequently during afternoon temperature spike (34°C).',
    ],
    outfit_suggestion: 'Breathable travel blazer, comfortable cotton pants, slip-on shoes for airport security.',
    activity_adjustments: [
      'Shifted morning standup to async text update due to flight departure.',
      'Created 2-hour offline deep work block during transit.',
    ],
    gmail_events: [
      {
        subject: 'Flight Confirmation: DEL -> BLR (AI 804)',
        from: 'reservations@airindia.in',
        snippet: 'Departure 06:15 AM from Terminal 3. Boarding gate opens 05:30 AM.',
        date: '2026-09-26T06:15:00Z',
        has_outdoor: false,
        has_travel: true,
      },
    ],
    gmail_summary: '✈️ 1 flight reservation detected · Departure 06:15 AM',
    has_outdoor_plans: false,
    has_travel_plans: true,
    jira_tickets: [
      {
        key: 'INFRA-310',
        summary: 'Audit SSL certificates and DNS failover endpoints',
        priority: 'Medium',
        status: 'In Progress',
        issue_type: 'Task',
        estimated_hours: 2.5,
      },
    ],
    jira_estimated_hours: 2.5,
    jira_summary: '📋 1 medium-priority task · ~2.5h workload',
    github_prs: [
      {
        type: 'PR',
        number: 58,
        title: 'perf(cache): Enable Redis connection pooling',
        author: 'swytch-dev',
        state: 'open',
        draft: false,
        days_old: 1,
        url: 'https://github.com/swytchcode/day-planner/pull/58',
        estimated_hours: 2.0,
      },
    ],
    github_issues: [],
    github_estimated_hours: 2.0,
    github_summary: '🐙 1 open PR for review · ~2.0h workload',
    day_plan_timeline: [
      {
        id: 'block-1',
        time: '03:45 – 04:45',
        activity: 'Airport Commute to Delhi T3',
        category: 'commute',
        location: 'Cab / Airport Expressway',
        context: 'Reach airport 2.5 hours prior to domestic departure',
        completed: true,
      },
      {
        id: 'block-2',
        time: '04:45 – 06:15',
        activity: 'Security Check & Lounge Coffee',
        category: 'break',
        location: 'IGI Terminal 3 Lounge',
        context: 'Light email triage and gate boarding',
        completed: true,
      },
      {
        id: 'block-3',
        time: '06:15 – 08:45',
        activity: 'Flight Transit & Offline Code Review [PR #58]',
        category: 'deep_work',
        location: 'In-Flight (Air India 804)',
        context: 'Review PR #58 offline docs and architecture schema',
        completed: false,
      },
      {
        id: 'block-4',
        time: '08:45 – 10:00',
        activity: 'Arrival Transit & Hotel Check-in',
        category: 'commute',
        location: 'Destination Express Transit',
        context: 'Transit to hotel workspace',
        completed: false,
      },
      {
        id: 'block-5',
        time: '10:00 – 12:30',
        activity: '[Jira INFRA-310] SSL & DNS audit',
        category: 'deep_work',
        location: 'Hotel Remote Desk',
        context: 'Audit failover clusters and security certificates',
        completed: false,
      },
      {
        id: 'block-6',
        time: '12:30 – 13:30',
        activity: 'Lunch & Afternoon Hydration',
        category: 'break',
        location: 'Dining Lounge',
        context: 'Lunch break and temperature rest',
        completed: false,
      },
      {
        id: 'block-7',
        time: '13:30 – 15:30',
        activity: 'Afternoon Architecture Sync & Testing',
        category: 'meeting',
        location: 'Zoom Conference',
        context: 'Sync with backend infrastructure guild',
        completed: false,
      },
    ],
    notion_logged: true,
    notion_page_url: 'https://notion.so/swytchcode/Delhi-Travel-Briefing-2026-09-26',
    slack_message_sent: true,
    email_sent: true,
    resend_message_id: 're_delhi_travel_7712',
    execution_log: [
      '⚡ [LangGraph] Pipeline initialized for scenario: travel_day (Delhi)',
      '🌦️ [OpenWeather] 28.2°C Clear | High visibility confirmed',
      '📬 [Gmail] Detected flight AI 804 departure at 06:15 AM',
      '📋 [Jira] 1 maintenance issue (2.5h estimated)',
      '🐙 [GitHub] 1 PR review scheduled for flight transit (2.0h)',
      '🧠 [Gemini AI] Synthesized travel anchors with hybrid timeline',
      '📓 [Notion] Travel Day briefing published',
      '📢 [Slack] Posted travel status update to #engineering',
      '📧 [Resend] Dispatched travel day digest',
      '🏁 [LangGraph] Execution finished cleanly (690ms)',
    ],
    processed_at: '2026-09-26T00:20:00.000Z',
  },

  // Scenario 3: Sprint Crunch in NYC
  day_planner_office: {
    city: 'New York',
    weather_summary: '🌤️ New York: Crisp & clear autumn air | 19.2°C (feels like 18.5°C) | Humidity: 46% | Wind: 3.4 m/s',
    temperature_c: 19.2,
    feels_like_c: 18.5,
    humidity: 46,
    wind_speed: 3.4,
    weather_condition: 'Clear',
    weather_icon: '01d',
    weather_score: 91,
    risk_level: 'low',
    forecast_summary: '24h forecast: Crisp sunshine, gentle breeze, zero rain probability | Temps: 16°C – 22°C',
    weather_alerts: [],
    ai_summary:
      'Ideal autumn weather in New York with 19°C sunshine and pleasant walking conditions. Sprint deadline has 3 critical tickets and 2 PRs pending review. Highly recommend working from the office to collaborate in person with teammates and clear sprint blockers.',
    go_to_office: 'office',
    office_reason: 'Exceptional weather and high sprint delivery pressure make in-person office collaboration optimal.',
    estimated_productive_hours: 8.0,
    recommendations: [
      'Take subway or enjoy morning walk through Manhattan in crisp 19°C air.',
      'Book War Room for sprint demo prep at 14:00.',
      'Pair program with frontend lead to unblock PR #72.',
      'Wrap up critical Jira tickets before 16:30 sprint review.',
    ],
    outfit_suggestion: 'Smart casual layers, light bomber jacket, comfortable walking sneakers.',
    activity_adjustments: [
      'Scheduled in-person pair programming block in Manhattan office.',
      'Reserved 30-minute park walk lunch break at Bryant Park.',
    ],
    gmail_events: [
      {
        subject: 'Sprint 42 Demo & Review',
        from: 'scrummaster@swytchcode.dev',
        snippet: 'Meeting in 7th Floor Boardroom and Google Meet at 16:00.',
        date: '2026-09-26T16:00:00Z',
        has_outdoor: false,
        has_travel: false,
      },
    ],
    gmail_summary: '📋 1 sprint review calendar invite · In-person Boardroom',
    has_outdoor_plans: true,
    has_travel_plans: false,
    jira_tickets: [
      {
        key: 'SPRINT-801',
        summary: 'Finalize real-time WebSocket protocol for command center',
        priority: 'Highest',
        status: 'In Progress',
        issue_type: 'Story',
        estimated_hours: 3.5,
      },
      {
        key: 'SPRINT-804',
        summary: 'Add RFC 5545 iCalendar client exporter',
        priority: 'High',
        status: 'To Do',
        issue_type: 'Task',
        estimated_hours: 2.0,
      },
      {
        key: 'SPRINT-812',
        summary: 'Verify zero layout shift and 3-second aesthetic test',
        priority: 'High',
        status: 'To Do',
        issue_type: 'Task',
        estimated_hours: 1.5,
      },
    ],
    jira_estimated_hours: 7.0,
    jira_summary: '📋 3 critical sprint tickets · ~7.0h total workload',
    github_prs: [
      {
        type: 'PR',
        number: 72,
        title: 'feat(ui): 8-node swarm topology visualizer with glowing packets',
        author: 'swytch-dev',
        state: 'open',
        draft: false,
        days_old: 3,
        url: 'https://github.com/swytchcode/day-planner/pull/72',
        estimated_hours: 1.5,
      },
      {
        type: 'PR',
        number: 75,
        title: 'fix(terminal): Monospace audit log auto-scroll behavior',
        author: 'lead-eng',
        state: 'open',
        draft: false,
        days_old: 1,
        url: 'https://github.com/swytchcode/day-planner/pull/75',
        estimated_hours: 1.0,
      },
    ],
    github_issues: [],
    github_estimated_hours: 2.5,
    github_summary: '🐙 2 open PRs (PR #72 is 3 days stale!) · ~2.5h workload',
    day_plan_timeline: [
      {
        id: 'block-1',
        time: '08:15 – 09:00',
        activity: 'Manhattan Commute & Morning Walk',
        category: 'commute',
        location: 'Subway & Broadway Walk',
        context: 'Pleasant 19°C autumn walk to office',
        completed: true,
      },
      {
        id: 'block-2',
        time: '09:00 – 09:30',
        activity: 'Desk Setup & Sprint War Room Briefing',
        category: 'meeting',
        location: 'Office Floor 7',
        context: 'Align on sprint burndown goals',
        completed: false,
      },
      {
        id: 'block-3',
        time: '09:30 – 12:30',
        activity: '[Jira SPRINT-801] Real-time WS protocol implementation',
        category: 'deep_work',
        location: 'Engineering Pod B',
        context: 'High-focus deep work with live WebSocket testing',
        completed: false,
      },
      {
        id: 'block-4',
        time: '12:30 – 13:30',
        activity: 'Bryant Park Lunch & Sunshine Walk',
        category: 'break',
        location: 'Bryant Park',
        context: 'Outdoor recharge in optimal 20°C weather',
        completed: false,
      },
      {
        id: 'block-5',
        time: '13:30 – 15:00',
        activity: '[GitHub PR #72 & #75] Stale PR Code Review',
        category: 'deep_work',
        location: 'Focus Booth 3',
        context: 'Review stale PR #72 with interactive node visualizer',
        completed: false,
      },
      {
        id: 'block-6',
        time: '15:00 – 16:30',
        activity: '[Jira SPRINT-804] RFC 5545 iCal generator',
        category: 'deep_work',
        location: 'Engineering Pod B',
        context: 'Implement client-side calendar export',
        completed: false,
      },
      {
        id: 'block-7',
        time: '16:30 – 17:30',
        activity: 'Sprint Demo & Review Meeting',
        category: 'meeting',
        location: 'Boardroom 7A',
        context: 'Demonstrate Command Center frontend to stakeholders',
        completed: false,
      },
    ],
    notion_logged: true,
    notion_page_url: 'https://notion.so/swytchcode/NYC-Sprint-Briefing-2026-09-26',
    slack_message_sent: true,
    email_sent: true,
    resend_message_id: 're_nyc_sprint_5510',
    execution_log: [
      '⚡ [LangGraph] Pipeline initialized for scenario: day_planner_office (New York)',
      '🌦️ [OpenWeather] 19.2°C Clear | Score: 91/100',
      '📬 [Gmail] Sprint review calendar invite identified',
      '📋 [Jira] 3 critical sprint tickets fetched (7.0h)',
      '🐙 [GitHub] 2 PRs parsed · ⚠️ PR #72 flagged as 3 days stale',
      '🧠 [Gemini AI] High weather score + sprint urgency: Office verdict recommended',
      '📓 [Notion] Sprint briefing created',
      '📢 [Slack] Posted to #sprint-squad: Office day confirmed',
      '📧 [Resend] Dispatched morning sprint briefing',
      '🏁 [LangGraph] Pipeline completed in 610ms',
    ],
    processed_at: '2026-09-26T00:20:00.000Z',
  },

  // Scenario 4: Clear Friday in Mumbai
  clear_day: {
    city: 'Mumbai',
    weather_summary: '🌴 Mumbai: Warm tropical breeze, clear sunny skies | 29.5°C (feels like 32.8°C) | Humidity: 68% | Wind: 3.8 m/s',
    temperature_c: 29.5,
    feels_like_c: 32.8,
    humidity: 68,
    wind_speed: 3.8,
    weather_condition: 'Clear',
    weather_icon: '01d',
    weather_score: 84,
    risk_level: 'low',
    forecast_summary: '24h forecast: Bright sunshine, coastal breeze, mild evening | Temps: 26°C – 31°C',
    weather_alerts: [],
    ai_summary:
      'Pleasant coastal weather in Mumbai with mild sea breeze and bright skies. Friday team schedule includes an afternoon park picnic and sports sync. Workload is manageable with 1 feature ticket and 1 quick PR review. Office attendance strongly recommended to participate in team festivities.',
    go_to_office: 'office',
    office_reason: 'Optimal outdoor conditions and scheduled team social picnic make office attendance ideal.',
    estimated_productive_hours: 6.0,
    recommendations: [
      'Travel to BKC office before morning rush hour (08:30).',
      'Carry sunglasses and light linen attire for the afternoon picnic.',
      'Wrap up key code deliverables before 14:30 team outing.',
      'Stay hydrated in coastal 68% humidity.',
    ],
    outfit_suggestion: 'Breathable linen shirt, lightweight chinos, sunglasses, and comfortable sneakers.',
    activity_adjustments: [
      'Shifted afternoon sprint wrap-up to Monday morning to accommodate team picnic.',
      'Added 2-hour outdoor picnic and recreation block at MMRDA grounds.',
    ],
    gmail_events: [
      {
        subject: 'Friday Team Picnic & Outdoor Games',
        from: 'people-ops@swytchcode.dev',
        snippet: 'Meet at BKC MMRDA Park at 15:00 for team sports and picnic snacks.',
        date: '2026-09-26T15:00:00Z',
        has_outdoor: true,
        has_travel: false,
      },
    ],
    gmail_summary: '🎉 1 outdoor event detected · Team Picnic at 15:00',
    has_outdoor_plans: true,
    has_travel_plans: false,
    jira_tickets: [
      {
        key: 'MUM-118',
        summary: 'Finalize mobile responsive layouts for dashboard cards',
        priority: 'Medium',
        status: 'In Progress',
        issue_type: 'Task',
        estimated_hours: 3.0,
      },
    ],
    jira_estimated_hours: 3.0,
    jira_summary: '📋 1 medium task · ~3.0h workload',
    github_prs: [
      {
        type: 'PR',
        number: 62,
        title: 'feat(theme): Incident command center surface ladder tokens',
        author: 'iakankshaa',
        state: 'open',
        draft: false,
        days_old: 1,
        url: 'https://github.com/swytchcode/day-planner/pull/62',
        estimated_hours: 1.0,
      },
    ],
    github_issues: [],
    github_estimated_hours: 1.0,
    github_summary: '🐙 1 open PR review · ~1.0h workload',
    day_plan_timeline: [
      {
        id: 'block-1',
        time: '08:30 – 09:15',
        activity: 'Commute to BKC Office',
        category: 'commute',
        location: 'Western Express Highway / Sea Link',
        context: 'Smooth commute with pleasant sea breeze',
        completed: true,
      },
      {
        id: 'block-2',
        time: '09:15 – 10:00',
        activity: 'Morning Chai & Friday Standup',
        category: 'meeting',
        location: 'Cafeteria & Terrace',
        context: 'Team sync and weekend roadmap planning',
        completed: false,
      },
      {
        id: 'block-3',
        time: '10:00 – 12:30',
        activity: '[Jira MUM-118] Mobile responsive cards polish',
        category: 'deep_work',
        location: 'Workstation 4B',
        context: 'Complete responsive CSS layout testing',
        completed: false,
      },
      {
        id: 'block-4',
        time: '12:30 – 13:30',
        activity: 'Team Lunch at BKC Bistro',
        category: 'break',
        location: 'BKC Bistro',
        context: 'Lunch with product and design team',
        completed: false,
      },
      {
        id: 'block-5',
        time: '13:30 – 14:30',
        activity: '[GitHub PR #62] Review surface ladder tokens',
        category: 'deep_work',
        location: 'Focus Lounge',
        context: 'Final approve design system PR',
        completed: false,
      },
      {
        id: 'block-6',
        time: '15:00 – 17:30',
        activity: 'Team Park Picnic & Outdoor Games',
        category: 'break',
        location: 'MMRDA Park BKC',
        context: 'Team bonding and frisbee recreation in clear 29°C weather',
        completed: false,
      },
      {
        id: 'block-7',
        time: '17:30 – 18:15',
        activity: 'Commute Home & Weekend Wrap',
        category: 'commute',
        location: 'Sea Link Return Transit',
        context: 'Sunset commute along coastal link',
        completed: false,
      },
    ],
    notion_logged: true,
    notion_page_url: 'https://notion.so/swytchcode/Mumbai-Friday-Briefing-2026-09-26',
    slack_message_sent: true,
    email_sent: true,
    resend_message_id: 're_mumbai_clear_1044',
    execution_log: [
      '⚡ [LangGraph] Pipeline initialized for scenario: clear_day (Mumbai)',
      '🌴 [OpenWeather] 29.5°C Clear | Sea breeze: 3.8 m/s',
      '📬 [Gmail] Team picnic invitation confirmed at MMRDA Park',
      '📋 [Jira] 1 task fetched (3.0h estimated)',
      '🐙 [GitHub] 1 PR parsed (1.0h estimated)',
      '🧠 [Gemini AI] High weather score (84) + outdoor picnic: Office verdict synthesized',
      '📓 [Notion] Daily Briefing page created successfully',
      '📢 [Slack] Posted Friday update to #mumbai-team',
      '📧 [Resend] Dispatched weekend briefing digest',
      '🏁 [LangGraph] Pipeline complete with 0 errors (640ms)',
    ],
    processed_at: '2026-09-26T00:20:00.000Z',
  },
};

// Aliases matching preset keys
MOCK_RESPONSES['london-storm'] = MOCK_RESPONSES.storm_warning;
MOCK_RESPONSES['delhi-travel'] = MOCK_RESPONSES.travel_day;
MOCK_RESPONSES['nyc-sprint'] = MOCK_RESPONSES.day_planner_office;
MOCK_RESPONSES['mumbai-clear'] = MOCK_RESPONSES.clear_day;

export const DEFAULT_MOCK_RESPONSE: AgentResponse = MOCK_RESPONSES.storm_warning;
